# Generated by Django 4.1.4 on 2023-04-29 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRManagementSystemApp', '0004_alter_customuser_date_employment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='usedFreeDays',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='usedSickLeave',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='usedVacDays',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
